package cmd

// Endpoint is the public mobile API contract. Keep this list aligned with
// sunflower-backoffice/config/routes.rb; `api endpoints` and agent-context
// expose it without requiring agents to scrape Rails or --help.
type Endpoint struct {
	Method  string `json:"method"`
	Path    string `json:"path"`
	Summary string `json:"summary"`
	Body    string `json:"body,omitempty"`
}

var endpoints = []Endpoint{
	{"POST", "/api/mobile/v1/session", "Sign in and receive a bearer token", "email,password,otp_attempt?,device_name?,account_id?"}, {"DELETE", "/api/mobile/v1/session", "Sign out and revoke the current token", "notification_token?"}, {"POST", "/api/mobile/v1/users", "Register a user", "email,password,password_confirmation,first_name?,last_name?"}, {"POST", "/api/mobile/v1/confirmation", "Resend account confirmation", "email"}, {"POST", "/api/mobile/v1/password", "Request a password reset", "email"}, {"PATCH", "/api/mobile/v1/password", "Change password", "current_password,password,password_confirmation"}, {"PATCH", "/api/mobile/v1/password_reset", "Complete a password reset", "token,password,password_confirmation"},
	{"GET", "/api/mobile/v1/profile", "Get current user profile", ""}, {"PATCH", "/api/mobile/v1/profile", "Update profile", ""}, {"DELETE", "/api/mobile/v1/profile", "Delete profile", ""}, {"GET", "/api/mobile/v1/two_factor", "Get two-factor status", ""}, {"POST", "/api/mobile/v1/two_factor/setup", "Generate two-factor setup", ""}, {"POST", "/api/mobile/v1/two_factor", "Enable two-factor authentication", "otp_attempt"}, {"DELETE", "/api/mobile/v1/two_factor", "Disable two-factor authentication", "password"}, {"POST", "/api/mobile/v1/two_factor/backup_codes", "Regenerate backup codes", "otp_attempt"},
	{"GET", "/api/mobile/v1/account", "Get current account", ""}, {"PATCH", "/api/mobile/v1/account", "Update current account", "name"}, {"DELETE", "/api/mobile/v1/account", "Delete current account", ""}, {"POST", "/api/mobile/v1/account/transfer", "Transfer account ownership", "user_id"}, {"POST", "/api/mobile/v1/accounts", "Create an account", "name"}, {"GET", "/api/mobile/v1/accounts", "List accounts", ""}, {"GET", "/api/mobile/v1/account_members", "List account members", ""}, {"PATCH", "/api/mobile/v1/account_members/:id", "Update member roles", ""}, {"DELETE", "/api/mobile/v1/account_members/:id", "Remove account member", ""},
	{"GET", "/api/mobile/v1/invitations/:token", "Show an invitation", ""}, {"POST", "/api/mobile/v1/invitations", "Create invitation", "email,name?,roles?"}, {"PATCH", "/api/mobile/v1/invitations/:id", "Update invitation", ""}, {"POST", "/api/mobile/v1/invitations/:id/accept", "Accept invitation", ""}, {"DELETE", "/api/mobile/v1/invitations/:id/reject", "Reject invitation", ""}, {"POST", "/api/mobile/v1/invitations/:id/resend", "Resend invitation", ""}, {"DELETE", "/api/mobile/v1/invitations/:id", "Delete invitation", ""},
	{"GET", "/api/mobile/v1/bootstrap", "Fetch app bootstrap and feature configuration", ""}, {"GET", "/api/mobile/v1/schedule", "Fetch checkout-driven schedule", "from?,to?,property_id?"}, {"GET", "/api/mobile/v1/properties", "List properties", ""}, {"POST", "/api/mobile/v1/properties", "Create property", ""}, {"GET", "/api/mobile/v1/properties/:id", "Show property", ""}, {"PATCH", "/api/mobile/v1/properties/:id", "Update property", ""}, {"DELETE", "/api/mobile/v1/properties/:id", "Delete property", ""}, {"POST", "/api/mobile/v1/properties/:id/cleanings", "Create cleaning", ""}, {"POST", "/api/mobile/v1/properties/:id/inspections", "Create inspection", ""},
	{"GET", "/api/mobile/v1/cleanings/:id", "Show cleaning", ""}, {"POST", "/api/mobile/v1/cleanings/:id/pre_inspection", "Create pre-inspection", ""}, {"POST", "/api/mobile/v1/cleanings/:id/completion_evidences", "Upload completion evidence", ""}, {"POST", "/api/mobile/v1/cleanings/:id/complete", "Complete cleaning", ""}, {"GET", "/api/mobile/v1/inspections/:id", "Show inspection", ""}, {"POST", "/api/mobile/v1/inspections/:id/complete", "Complete inspection", ""}, {"GET", "/api/mobile/v1/pre_inspections/:id", "Show pre-inspection", ""}, {"GET", "/api/mobile/v1/tasks/:id", "Show task", ""}, {"PATCH", "/api/mobile/v1/tasks/:id", "Update task", ""}, {"POST", "/api/mobile/v1/tasks/:id/photo", "Upload task photo", ""},
	{"GET", "/api/mobile/v1/maintenance_assignments", "List maintenance assignments", "status?,mine?"}, {"POST", "/api/mobile/v1/maintenance_assignments", "Create maintenance assignment", ""}, {"GET", "/api/mobile/v1/maintenance_assignments/:id", "Show maintenance assignment", ""}, {"PATCH", "/api/mobile/v1/maintenance_assignments/:id", "Update maintenance assignment", ""}, {"DELETE", "/api/mobile/v1/maintenance_assignments/:id", "Delete maintenance assignment", ""}, {"POST", "/api/mobile/v1/maintenance_assignments/:id/complete", "Complete maintenance assignment", ""}, {"GET", "/api/mobile/v1/properties/:id/maintenance_items", "List maintenance items", ""}, {"POST", "/api/mobile/v1/properties/:id/maintenance_items", "Create maintenance item", ""}, {"POST", "/api/mobile/v1/properties/:id/maintenance_items/bootstrap", "Maintenance catalog bootstrap", ""}, {"GET", "/api/mobile/v1/maintenance_items/:id", "Show maintenance item", ""}, {"PATCH", "/api/mobile/v1/maintenance_items/:id", "Update maintenance item", ""}, {"DELETE", "/api/mobile/v1/maintenance_items/:id", "Delete maintenance item", ""}, {"POST", "/api/mobile/v1/maintenance_items/:id/mark_performed", "Mark maintenance performed", ""}, {"GET", "/api/mobile/v1/properties/:id/maintenance_suggestion", "Get maintenance suggestion", ""}, {"POST", "/api/mobile/v1/properties/:id/maintenance_suggestion", "Create maintenance suggestion", ""}, {"POST", "/api/mobile/v1/properties/:id/maintenance_suggestion/schedule", "Schedule suggestion", ""},
	{"GET", "/api/mobile/v1/properties/:id/inventories", "List inventory", ""}, {"POST", "/api/mobile/v1/properties/:id/inventories", "Create inventory item", ""}, {"POST", "/api/mobile/v1/properties/:id/inventories/bootstrap", "Inventory bootstrap", ""}, {"GET", "/api/mobile/v1/properties/:id/inventories/forecast", "Inventory forecast", "forecast_days?"}, {"GET", "/api/mobile/v1/inventories/:id", "Show inventory item", ""}, {"PATCH", "/api/mobile/v1/inventories/:id", "Update inventory item", ""}, {"DELETE", "/api/mobile/v1/inventories/:id", "Delete inventory item", ""}, {"POST", "/api/mobile/v1/inventories/:id/counts", "Record inventory count", "count,observed_at?"},
	{"GET", "/api/mobile/v1/notifications", "List notifications", "limit?"}, {"GET", "/api/mobile/v1/notifications/:id", "Show notification", ""}, {"POST", "/api/mobile/v1/notifications/mark_all_read", "Mark notifications read", ""}, {"POST", "/api/mobile/v1/notification_tokens", "Register push token", "token,platform?"}, {"GET", "/api/mobile/v1/announcements", "List announcements", "limit?"}, {"GET", "/api/mobile/v1/announcements/:id", "Show announcement", ""}, {"GET", "/api/mobile/v1/agreements", "List agreements", ""}, {"PATCH", "/api/mobile/v1/agreements/:id", "Accept agreement", ""},
	{"GET", "/api/mobile/v1/api_tokens", "List API tokens", ""}, {"POST", "/api/mobile/v1/api_tokens", "Create API token", "name,expires_at?"}, {"PATCH", "/api/mobile/v1/api_tokens/:id", "Update API token", ""}, {"DELETE", "/api/mobile/v1/api_tokens/:id", "Revoke API token", ""}, {"GET", "/api/mobile/v1/connected_accounts", "List connected accounts", ""}, {"DELETE", "/api/mobile/v1/connected_accounts/:id", "Disconnect account", ""}, {"POST", "/api/mobile/v1/voice_command", "Run a voice command", "command"},
	{"GET", "/api/mobile/v1/task_templates", "List task templates", ""}, {"POST", "/api/mobile/v1/task_templates", "Create task template", ""}, {"GET", "/api/mobile/v1/task_templates/:id", "Show task template", ""}, {"PATCH", "/api/mobile/v1/task_templates/:id", "Update task template", ""}, {"DELETE", "/api/mobile/v1/task_templates/:id", "Delete task template", ""}, {"POST", "/api/mobile/v1/task_templates/:id/ai", "Generate template with AI", ""}, {"POST", "/api/mobile/v1/task_templates/:id/tasks", "Add template task", ""}, {"GET", "/api/mobile/v1/inspection_templates", "List inspection templates", ""}, {"POST", "/api/mobile/v1/inspection_templates", "Create inspection template", ""}, {"GET", "/api/mobile/v1/inspection_templates/:id", "Show inspection template", ""}, {"PATCH", "/api/mobile/v1/inspection_templates/:id", "Update inspection template", ""}, {"DELETE", "/api/mobile/v1/inspection_templates/:id", "Delete inspection template", ""}, {"POST", "/api/mobile/v1/inspection_templates/:id/ai", "Generate inspection template with AI", ""}, {"POST", "/api/mobile/v1/inspection_templates/:id/tasks", "Add inspection task", ""}, {"PATCH", "/api/mobile/v1/template_tasks/:id", "Update template task", ""}, {"DELETE", "/api/mobile/v1/template_tasks/:id", "Delete template task", ""}, {"POST", "/api/mobile/v1/template_tasks/:id/move", "Move template task", ""},
}
